package travel.com.touristesTripResults.models

data class DataItem(val date: String = "",
                    val endDate: String = "",
                    val tripDaysCount: String = "",
                    val entertainmentServiceTypes: List<EntertainmentServiceTypesItem>?,
                    val country: Country,
                    val city: City,
                    val subCategory: SubCategory,
                    val createdAt: String = "",
                    val title: String = "",
                    val hotelDec: String = "",
                    val tripDays: List<TripDaysItem>?,
                    val hasParking: String = "",
                    val checkOut: String = "",
                    val categoryId: String = "",
                    val updatedAt: String = "",
                    val roomTypes: List<RoomTypesItem>?,
                    val price: String = "",
                    val subCategoryId: String = "",
                    val tripCommentsCount: String = "",
                    val member: Member,
                    val priceChl: String = "",
                    val id: Int = 0,
                    val importantInfo: String = "",
                    val priceChl: String = "",
                    val lat: String = "",
                    val startDate: String = "",
                    val memberId: String = "",
                    val foodTypes: List<FoodTypesItem>?,
                    val image: String = "",
                    val hotelItems: HotelItems,
                    val isActive: String = "",
                    val lng: String = "",
                    val checkIn: String = "",
                    val tripImages: List<TripImagesItem>?,
                    val priceDbl: String = "",
                    val tripComments: List<TripCommentsItem>?,
                    val priceTpl: String = "",
                    val stars: Int = 0,
                    val allowPets: String = "",
                    val hasInternet: String = "",
                    val cancellationPolicy: String = "",
                    val mediaTypes: List<MediaTypesItem>?,
                    val category: Category,
                    val countryId: String = "",
                    val cityId: String = "")