package travel.com.touristesTripResults.models

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize


@Parcelize
data class DataItem(val date: String? = "",
                    val end_date: String? = "",
                    val trip_days_count: String? = "",
                    val entertainment_service_types: List<EntertainmentServiceTypesItem>? = null,
                    val country: Country? = null,
                    val city: City? = null,
                    val sub_category: SubCategory? = null,
                    val created_at: String? = "",
                    val title: String? = "",
                    val hotel_dec: String? = "",
                    val trip_days: List<TripDaysItem>? = null,
                    val has_parking: String? = "",
                    val check_out: String? = "",
                    val category_id: String? = "",
                    val updated_at: String? = "",
                    val room_types: List<RoomTypesItem>? = null,
                    val price: String? = "",
                    val sub_category_id: String? = "",
                    val trip_comments_count: String? = "",
                    val member: Member? = null,
                    val price_chl: String? = "",
                    val id: Int? = 0,
                    val important_info: String? = "",
                    val lat: String? = "",
                    val start_date: String? = "",
                    val member_id: String? = "",
                    val food_types: List<FoodTypesItem>? = null,
                    val image: String? = "",
                    val hotel_items: HotelItems? = null,
                    val is_active: String? = "",
                    val lng: String? = "",
                    val check_in: String? = "",
                    val trip_images: List<TripImagesItem>? = null,
                    val price_dbl: String? = "",
                    val trip_comments: List<TripCommentsItem>? = null,
                    val price_tpl: String? = "",
                    val stars: Int? = 0,
                    val allow_pets: String? = "",
                    val hasInternet: String? = "",
                    val cancellation_policy: String? = "",
                    val media_types: List<MediaTypesItem>? = null,
                    val category: Category? = null,
                    val country_id: String? = "",
                    val city_id: String? = ""): Parcelable