package travel.com.myBookings.models

data class Trip(val date: String = "",
                val endDate: String = "",
                val createdAt: String = "",
                val title: String = "",
                val hotelDec: String = "",
                val hasParking: String = "",
                val checkOut: String = "",
                val categoryId: String = "",
                val updatedAt: String = "",
                val price: String = "",
                val subCategoryId: String = "",
                val priceChl: String = "",
                val id: Int = 0,
                val importantInfo: String = "",
                val priceChl: String = "",
                val lat: String = "",
                val startDate: String = "",
                val memberId: String = "",
                val image: String = "",
                val hotelItems: HotelItems,
                val isActive: String = "",
                val lng: String = "",
                val checkIn: String = "",
                val priceDbl: String = "",
                val priceTpl: String = "",
                val stars: Int = 0,
                val allowPets: String = "",
                val hasInternet: String = "",
                val cancellationPolicy: String = "",
                val countryId: String = "",
                val cityId: String = "")